---
name: openfortivpn
summary: openfortivpn, a PPP+SSL VPN client
description: |
    Openfortivpn is a client for PPP+SSL VPN tunnel services.
    It spawns a pppd process and operates the communication between
    the gateway and this process.
license: GPL-3.0
adopt-info: openfortivpn
base: core
confinement: strict
grade: stable

icon: snap/gui/icon.svg

architectures:
    - build-on: amd64

layout:
    /etc/openfortivpn:
        bind: $SNAP_COMMON

apps:
    openfortivpn:
        command: openfortivpn
        plugs:
            - network-bind
            - ppp
            - network-control

parts:
    openfortivpn:
        source: https://github.com/adrienverge/openfortivpn.git
        plugin: autotools
        configflags:
            - --with-pppd=/usr/sbin/pppd
            - --with-resolvconf=/sbin/resolvconf
        build-packages:
            - git
            - build-essential
            - pkg-config
            - libssl-dev
            - libsystemd-dev
        stage:
            - bin/openfortivpn
            - share/*
        # Infer version from Git tags:
        # * Remove the leading "v" from openfortivpn Git tags.
        # * We propose specific Git tags for openfortivpn snaps, if needed.
        #   Thay have a leading "sv" for "snap version" and we remove this
        #   leading "sv" too.
        # Infer grade from version:
        # * Tagged commits are considered "stable".
        # * Other commits are considered "devel".
        override-pull: |
            snapcraftctl pull
            version="$(git -C "${SNAPCRAFT_PART_SRC}" describe --tags | sed -e 's/^v//;s/-/+git/;y/-/./')"
            snapcraftctl set-version "$version"
