#!/bin/sh -e

OPENFORTIVPN_TEMPLATE="${SNAP}/share/openfortivpn/config.template"
OPENFORTIVPN_CONFIG="${SNAP_COMMON}/config"

sed -e '/^#/n;/^\s*$/n;s/^/# /' "$OPENFORTIVPN_TEMPLATE" > "$OPENFORTIVPN_CONFIG"
chmod 600 "$OPENFORTIVPN_CONFIG"
